ALTER TABLE "questions"
ADD COLUMN "topic" TEXT NOT NULL DEFAULT 'Tema geral',
ADD COLUMN "unit" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "questions"
ALTER COLUMN "topic" DROP DEFAULT,
ALTER COLUMN "unit" DROP DEFAULT;
